matrix_analysis.py
------------------
Utilities for comparing AHP matrices generated by different sources
(e.g. human experts vs. LLM outputs) and computing alignment metrics.

Used in dissertation research to benchmark LLM-generated pairwise
comparison matrices against published expert judgements.

Author: Rafi Khandoker
Institution: University of Leeds
"""

import numpy as np
from src.ahp import AHPMatrix


def frobenius_distance(matrix_a, matrix_b):
    """
    Computes the Frobenius distance between two matrices.

    The Frobenius distance measures element-wise difference between matrices.
    A lower value indicates closer alignment between the two sets of
    pairwise judgements.

    Parameters
    ----------
    matrix_a : list or numpy.ndarray
        First pairwise comparison matrix (e.g. expert-elicited).
    matrix_b : list or numpy.ndarray
        Second pairwise comparison matrix (e.g. LLM-generated).

    Returns
    -------
    float
        The Frobenius norm of the difference matrix.
    """
    a = np.array(matrix_a, dtype=float)
    b = np.array(matrix_b, dtype=float)
    return float(np.linalg.norm(a - b, 'fro'))


def priority_vector_similarity(matrix_a, matrix_b):
    """
    Computes the cosine similarity between the priority vectors of two matrices.

    Cosine similarity of 1.0 indicates identical relative priority rankings.
    Values closer to 1.0 indicate stronger alignment between the two sources
    of expert judgement.

    Parameters
    ----------
    matrix_a : list or numpy.ndarray
        First pairwise comparison matrix.
    matrix_b : list or numpy.ndarray
        Second pairwise comparison matrix.

    Returns
    -------
    float
        Cosine similarity between priority vectors, in range [-1, 1].
        Values close to 1.0 indicate strong alignment.
    """
    pv_a = AHPMatrix(matrix_a).priority_vector()
    pv_b = AHPMatrix(matrix_b).priority_vector()

    cosine_sim = np.dot(pv_a, pv_b) / (
        np.linalg.norm(pv_a) * np.linalg.norm(pv_b)
    )
    return float(cosine_sim)


def compare_matrices(expert_matrix, llm_matrix, label="LLM"):
    """
    Produces a full comparison report between an expert matrix and an
    LLM-generated matrix.

    Parameters
    ----------
    expert_matrix : list or numpy.ndarray
        The benchmark matrix from published human expert judgements.
    llm_matrix : list or numpy.ndarray
        The matrix generated by an LLM (e.g. GPT-4 or Claude).
    label : str, optional
        Name of the LLM for display purposes (default: "LLM").

    Returns
    -------
    dict
        A dictionary containing:
        - 'expert_cr': Consistency ratio of the expert matrix
        - 'llm_cr': Consistency ratio of the LLM matrix
        - 'frobenius_distance': Element-wise difference
        - 'priority_vector_similarity': Cosine similarity of weights
        - 'llm_is_consistent': Whether LLM matrix meets CR < 0.10
    """
    expert = AHPMatrix(expert_matrix)
    llm = AHPMatrix(llm_matrix)

    results = {
        'expert_cr': expert.consistency_ratio(),
        'llm_cr': llm.consistency_ratio(),
        'frobenius_distance': frobenius_distance(expert_matrix, llm_matrix),
        'priority_vector_similarity': priority_vector_similarity(
            expert_matrix, llm_matrix
        ),
        'llm_is_consistent': llm.is_consistent()
    }

    print(f"\nComparison: Expert vs {label}")
    print("-" * 45)
    print(f"Expert CR:                  {results['expert_cr']:.4f}")
    print(f"{label} CR:               {results['llm_cr']:.4f}")
    print(f"Frobenius Distance:         {results['frobenius_distance']:.4f}")
    print(f"Priority Vector Similarity: "
          f"{results['priority_vector_similarity']:.4f}")
    print(f"{label} Consistent:       {results['llm_is_consistent']}")

    return results
